In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv('data.csv')
dataset=df.drop(columns=['Model'])
dataset=dataset.dropna(how='any')
X=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values


Note:due to the fact that the dataset contains a lot of string values which is very useful in terms of prediction/accuracy hemnce we encode them 

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
X[:,0]=le.fit_transform(X[:,0])
X[:,2]=le.fit_transform(X[:,2])
X[:,5]=le.fit_transform(X[:,5])
X[:,6]=le.fit_transform(X[:,6])
X[:,8]=le.fit_transform(X[:,8])
X[:,9]=le.fit_transform(X[:,9])
X[:,10]=le.fit_transform(X[:,10])
print(X)


[[4 2011 6 ... 26 19 3916]
 [4 2011 6 ... 28 19 3916]
 [4 2011 6 ... 28 20 3916]
 ...
 [0 2012 6 ... 23 16 204]
 [0 2013 5 ... 23 16 204]
 [25 2006 7 ... 26 17 61]]


In [ ]:
y=y.reshape(len(y),1)
print(y)

[[46135]
 [40650]
 [36350]
 ...
 [50620]
 [50920]
 [28995]]


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [ ]:
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state = 0)
regressor.fit(X_train, y_train)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=0, splitter='best')

In [ ]:
y_pred=regressor.predict(X_test)

In [ ]:
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[ 23170.    23225.  ]
 [ 51231.67  55305.  ]
 [ 17250.    15945.  ]
 ...
 [102645.    95895.  ]
 [ 16095.    17395.  ]
 [ 37850.    41700.  ]]


Accuracy test:

In [ ]:
from sklearn.metrics import r2_score
a=r2_score(y_test, y_pred)
print(abs(a*100))

95.85125768340144


Note: From the above table we observe that accuracy of decision tree Regressor is good for huge datasets due to the fact that they are built for that reason